import IPNPCNS.Model.Population
import IPNPCNS.Cone.ProjectionStructure

/-!
# Constructive active-face regions

This module gives a finite-generator certificate for equation (199). A selected
generator set determines a candidate face span. Nonnegative selected coefficients and
nonpositive residual pairings with every ambient generator are sufficient to identify
orthogonal projection onto that span with metric projection onto the generated cone.

The inequalities are deliberately non-strict. Boundary points may therefore carry
more than one valid active certificate; a uniqueness theorem below proves that all
valid certificates return the same cone projection. No claim of necessity is made.
-/

open Set
open scoped BigOperators

namespace IPNPCNS

noncomputable section

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

/-- The closed cone of vectors pairing nonpositively with a fixed vector. -/
def nonpositiveInnerHalfspace (z : H) : ClosedCone H where
  toSubmodule :=
    { carrier := {y | inner ℝ z y ≤ 0}
      zero_mem' := by simp
      add_mem' := by
        intro x y hx hy
        change inner ℝ z (x + y) ≤ 0
        rw [inner_add_right]
        exact add_nonpos hx hy
      smul_mem' := by
        intro c x hx
        change inner ℝ z ((c : ℝ) • x) ≤ 0
        rw [inner_smul_right]
        exact mul_nonpos_of_nonneg_of_nonpos c.property hx }
  isClosed' := isClosed_le (continuous_const.inner continuous_id) continuous_const

/-- A vector lies in the polar of a closed conic hull exactly when it pairs
nonpositively with every generator. -/
theorem mem_polar_conicHull_iff {z : H} {s : Set H} [CompleteSpace H] :
    z ∈ polar (conicHull s) ↔ ∀ y ∈ s, inner ℝ z y ≤ 0 := by
  constructor
  · intro hz y hy
    exact (mem_polar.mp hz) y (subset_conicHull s hy)
  · intro hz
    rw [mem_polar]
    have hle : conicHull s ≤ nonpositiveInnerHalfspace z := conicHull_le hz
    intro y hy
    exact hle hy

variable {ι : Type*} [DecidableEq ι]
  [CompleteSpace H]

/-- The closed cone generated by the finite ambient index set. -/
def finiteGeneratedCone (g : ι → H) (I : Finset ι) : ClosedCone H :=
  conicHull (g '' (I : Set ι))

/-- The linear span of the selected generators, corresponding to `span(F)`. -/
def selectedFaceSpan (g : ι → H) (J : Finset ι) : Submodule ℝ H :=
  Submodule.span ℝ (g '' (J : Set ι))

omit [DecidableEq ι] [CompleteSpace H] in
/-- A span generated by finitely many face vectors has an orthogonal projection even
when the ambient Hilbert space is infinite-dimensional. -/
noncomputable instance selectedFaceSpan_hasOrthogonalProjection
    (g : ι → H) (J : Finset ι) :
    (selectedFaceSpan g J).HasOrthogonalProjection := by
  letI : FiniteDimensional ℝ (selectedFaceSpan g J) :=
    FiniteDimensional.span_of_finite ℝ (J.finite_toSet.image g)
  letI : CompleteSpace (selectedFaceSpan g J) :=
    FiniteDimensional.complete ℝ _
  exact inferInstance

omit [DecidableEq ι] [CompleteSpace H] in
/-- The closed cone generated by a finite family is contained in the real span of
that family. -/
theorem finiteGeneratedCone_le_selectedFaceSpan
    (g : ι → H) (I : Finset ι) :
    ∀ x ∈ finiteGeneratedCone g I, x ∈ selectedFaceSpan g I := by
  letI : FiniteDimensional ℝ (selectedFaceSpan g I) :=
    FiniteDimensional.span_of_finite ℝ (I.finite_toSet.image g)
  intro x hx
  change x ∈ closure (PointedCone.hull ℝ (g '' (I : Set ι))) at hx
  apply (Submodule.closed_of_finiteDimensional (selectedFaceSpan g I)).closure_subset_iff.2
    (PointedCone.hull_le_span ℝ (g '' (I : Set ι))) hx

omit [DecidableEq ι] [CompleteSpace H] in
/-- Taking a closed conic hull does not change the real span of a finite generator
family. -/
theorem coneSpan_finiteGeneratedCone_eq_selectedFaceSpan
    (g : ι → H) (I : Finset ι) :
    coneSpan (finiteGeneratedCone g I) = selectedFaceSpan g I := by
  apply le_antisymm
  · apply Submodule.span_le.2
    exact finiteGeneratedCone_le_selectedFaceSpan g I
  · apply Submodule.span_le.2
    rintro y ⟨i, hi, rfl⟩
    apply Submodule.subset_span
    exact subset_conicHull _ ⟨i, hi, rfl⟩

omit [DecidableEq ι] [CompleteSpace H] in
/-- The real span of a finitely generated cone is finite-dimensional, independently
of the dimension of the ambient space. -/
theorem finiteDimensional_coneSpan_finiteGeneratedCone
    (g : ι → H) (I : Finset ι) :
    FiniteDimensional ℝ (coneSpan (finiteGeneratedCone g I)) := by
  rw [coneSpan_finiteGeneratedCone_eq_selectedFaceSpan g I]
  exact FiniteDimensional.span_of_finite ℝ (I.finite_toSet.image g)

omit [DecidableEq ι] in
/-- Equation (195) for the paper's finitely generated population cone. The ambient
Hilbert space need not be finite-dimensional. -/
theorem metricProjection_finiteGeneratedCone_span
    (g : ι → H) (I : Finset ι) (x : H) :
    metricProjection (finiteGeneratedCone g I) x =
      metricProjection (finiteGeneratedCone g I)
        ((selectedFaceSpan g I).starProjection x) := by
  symm
  apply metricProjection_starProjection_eq
  exact finiteGeneratedCone_le_selectedFaceSpan g I

/-- Orthogonal projection onto the selected face span in equations (199)–(200). -/
def selectedFaceProjection (g : ι → H) (J : Finset ι) (x : H) : H :=
  (selectedFaceSpan g J).starProjection x

/-- Sufficient active-set conditions for one projection piece.

The selected set is contained in the ambient generator set; the span projection has a
nonnegative selected-generator expansion; and its residual pairs nonpositively with
every ambient generator. Zero coefficients and zero residual pairings are admitted so
that face boundaries are covered. -/
def ActiveFaceCertificate
    (g : ι → H) (I J : Finset ι) (x : H) : Prop :=
  J ⊆ I ∧ ∃ c : ι → ℝ,
    (∀ i ∈ J, 0 ≤ c i) ∧
    selectedFaceProjection g J x = ∑ i ∈ J, c i • g i ∧
    ∀ i ∈ I, inner ℝ (x - selectedFaceProjection g J x) (g i) ≤ 0

/-- The active region certified for the selected generator set. -/
def activeFaceRegion (g : ι → H) (I J : Finset ι) : Set H :=
  {x | ActiveFaceCertificate g I J x}

omit [DecidableEq ι] [CompleteSpace H] in
/-- Every indexed generator belongs to its closed generated cone. -/
theorem generator_mem_finiteGeneratedCone
    (g : ι → H) (I : Finset ι) {i : ι} (hi : i ∈ I) :
    g i ∈ finiteGeneratedCone g I := by
  apply subset_conicHull
  exact ⟨i, hi, rfl⟩

omit [DecidableEq ι] [CompleteSpace H] in
/-- The nonnegative selected combination is feasible in the ambient cone. -/
theorem selectedFaceProjection_mem_finiteGeneratedCone
    (g : ι → H) (I J : Finset ι) (x : H)
    (h : ActiveFaceCertificate g I J x) :
    selectedFaceProjection g J x ∈ finiteGeneratedCone g I := by
  rcases h with ⟨hJI, c, hc, hcomb, hres⟩
  rw [hcomb]
  apply (finiteGeneratedCone g I).sum_mem
  intro i hi
  exact (finiteGeneratedCone g I).smul_mem
    (generator_mem_finiteGeneratedCone g I (hJI hi)) (hc i hi)

omit [DecidableEq ι] in
/-- The finite residual inequalities certify membership in the polar of the complete
closed generated cone. -/
theorem activeFaceResidual_mem_polar
    (g : ι → H) (I J : Finset ι) (x : H)
    (h : ActiveFaceCertificate g I J x) :
    x - selectedFaceProjection g J x ∈ polar (finiteGeneratedCone g I) := by
  rcases h with ⟨hJI, c, hc, hcomb, hres⟩
  rw [finiteGeneratedCone, mem_polar_conicHull_iff]
  rintro y ⟨i, hi, rfl⟩
  exact hres i hi

omit [DecidableEq ι] [CompleteSpace H] in
/-- Orthogonal projection onto the selected span is orthogonal to its residual. -/
theorem inner_selectedFaceProjection_residual_eq_zero
    (g : ι → H) (J : Finset ι) (x : H) :
    inner ℝ (selectedFaceProjection g J x)
        (x - selectedFaceProjection g J x) = 0 := by
  have hproj : selectedFaceProjection g J x ∈ selectedFaceSpan g J :=
    Submodule.starProjection_apply_mem _ _
  have hres : x - selectedFaceProjection g J x ∈ (selectedFaceSpan g J)ᗮ :=
    Submodule.sub_starProjection_mem_orthogonal x
  have hzero := ((Submodule.mem_orthogonal' (selectedFaceSpan g J)
    (x - selectedFaceProjection g J x)).mp hres)
    (selectedFaceProjection g J x) hproj
  simpa [real_inner_comm] using hzero

omit [DecidableEq ι] in
/-- Constructive equation (199): the finite active-face certificate identifies the
cone projection with projection onto the selected face span. -/
theorem metricProjection_finiteGeneratedCone_eq_selectedFaceProjection
    (g : ι → H) (I J : Finset ι) (x : H)
    (h : ActiveFaceCertificate g I J x) :
    metricProjection (finiteGeneratedCone g I) x = selectedFaceProjection g J x := by
  rw [metricProjection_eq_iff]
  exact ⟨selectedFaceProjection_mem_finiteGeneratedCone g I J x h,
    activeFaceResidual_mem_polar g I J x h,
    inner_selectedFaceProjection_residual_eq_zero g J x⟩

omit [DecidableEq ι] [CompleteSpace H] in
/-- The degenerate face has zero span projection. -/
theorem selectedFaceProjection_empty (g : ι → H) (x : H) :
    selectedFaceProjection g ∅ x = 0 := by
  simp [selectedFaceProjection, selectedFaceSpan]

omit [DecidableEq ι] [CompleteSpace H] in
/-- The active region for the zero face consists exactly of vectors satisfying all
ambient polar inequalities. -/
theorem mem_activeFaceRegion_empty_iff
    (g : ι → H) (I : Finset ι) (x : H) :
    x ∈ activeFaceRegion g I ∅ ↔
      ∀ i ∈ I, inner ℝ x (g i) ≤ 0 := by
  constructor
  · rintro ⟨hsub, c, hc, hcomb, hres⟩ i hi
    simpa [selectedFaceProjection_empty] using hres i hi
  · intro hres
    refine ⟨by simp, fun _ => 0, by simp, ?_, ?_⟩
    · simp [selectedFaceProjection_empty]
    · intro i hi
      simpa [selectedFaceProjection_empty] using hres i hi

omit [DecidableEq ι] in
/-- On the certified zero-face region, cone projection is the zero vector. -/
theorem metricProjection_finiteGeneratedCone_eq_zero_of_empty_certificate
    (g : ι → H) (I : Finset ι) (x : H)
    (h : x ∈ activeFaceRegion g I ∅) :
    metricProjection (finiteGeneratedCone g I) x = 0 := by
  rw [metricProjection_finiteGeneratedCone_eq_selectedFaceProjection g I ∅ x h,
    selectedFaceProjection_empty]

omit [DecidableEq ι] in
/-- Boundary overlap is harmless: any two valid active certificates return the same
projected point. -/
theorem selectedFaceProjection_eq_of_mem_activeFaceRegions
    (g : ι → H) (I J K : Finset ι) (x : H)
    (hJ : x ∈ activeFaceRegion g I J)
    (hK : x ∈ activeFaceRegion g I K) :
    selectedFaceProjection g J x = selectedFaceProjection g K x := by
  rw [← metricProjection_finiteGeneratedCone_eq_selectedFaceProjection g I J x hJ,
    ← metricProjection_finiteGeneratedCone_eq_selectedFaceProjection g I K x hK]

/-- Build the conditional population interface from a constructive finite active-face
certificate. Its `projection_eq_face` field is now a theorem rather than a premise. -/
def PopulationRegion.ofFiniteActiveFace
    (source : ClosedCone H) (messageModel : Set H) (populationMap : H → H)
    (g : ι → H) (I J : Finset ι) : PopulationRegion H where
  source := source
  target := finiteGeneratedCone g I
  messageModel := messageModel
  region := activeFaceRegion g I J
  faceProjection := selectedFaceProjection g J
  populationMap := populationMap
  projection_eq_face := fun u hu =>
    metricProjection_finiteGeneratedCone_eq_selectedFaceProjection g I J u hu

end

end IPNPCNS
